apiVersion: apps/v1
kind: Deployment
metadata:
  name: trendstore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trendstore
  template:
    metadata:
      labels:
        app: trendstore
    spec:
      containers:
      - name: trendstore
        image: nginx:mainline
        ports:
        - containerPort: 3000
